package it.estar.time_counter.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalTime;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "calendars_times")
public class CalendarTime {
    @Id
    private Long id;
    @Column(name = "calendar_time")
    private LocalTime calendarTime;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "calendar_date", nullable = false)
    private CalendarDate calendarDate;

    //constructors getter and setter generated by lombok
}
