package it.estar.time_counter.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name= "calendars_dates")
public class CalendarDate {
    @Id
    private Long id;
    @Column(name = "calendar_date", nullable = false)
    private LocalDate calendarDate;

    @OneToMany(
            mappedBy = "calendars_dates",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<CalendarTime> calendarTimes = new ArrayList<>();

    //constructors getter and setter generated by lombok
}
